services:
  web:
    image: lueylu/nlq-api:v1.0.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    # removed --reload for production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
    #restart: always

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email lueyiyornumbe@punch.agency --agree-tos --no-eff-email -d redcloud.punchapps.cool
    #command: renew
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
